Feat/apiv2 update
Seagate/seagate-exos-x-csi pull request #94
Opened 2023-10-06 19:34 UTC by David-T-White

This PR integrates the new version of [api-lib](https://github.com/Seagate/seagate-exos-x-api-go), utilizing the /pkg/v1 library, shown in go.mod as v1.0.18.  

It rebases the original "apiv2" branch onto main, and then adds a few bug fixes.

Bug fixes:
- Update csi snapshot object creation using new api lib to directly use the CreationTime returned from the snapshot lib, instead of re-parsing the creation time string.
- Volume WWN previously might not be retrieved if createVolume was called a second time for the same volume (CSI idempotency requirement).
- Restore "previously unmapped device discovery" functionality

2023-10-11 21:10 UTC, jskazinski requested changes
Perhaps one change to reduce an extra MC API call for WWN.

2023-10-11 21:57 UTC, David-T-White commented on pkg/controller/provisioner.go
> +	wwn, err = controller.client.GetVolumeWwn(volumeName)
Good point, I reinstated the previous version that utilizes the volume object returned from Create Volume, and check for empty wwn before doing the GetVolumeWwwn call.

2023-10-11 22:10 UTC, jskazinski approved these changes
LGTM

2023-10-12 19:19 UTC, seagate-chris approved these changes

2023-10-13 15:17 UTC, merged